# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Benchmark PRs
on:
  push:
    branches-ignore: [main]

jobs:
  compare_main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: benchmarks # ${{ github.event.repository.default_branch }}
          path: main

      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          path: current

      - name: Setup Python for main branch
        uses: actions/setup-python@v5
        id: python-main
        with:
          python-version: "3.13"
          cache: pip
          cache-dependency-path: main/setup.py
      - run: cd main && pip --python '${{ steps.python-main.outputs.python-path }}' install ".[dev]"
      - run: cd main && pip --python '${{ steps.python-main.outputs.python-path }}' install pytest-benchmark # temporary until main branch has it

      - name: Setup Python for current branch
        uses: actions/setup-python@v5
        id: python-current
        with:
          python-version: "3.13"
          cache: pip
          cache-dependency-path: current/setup.py
      - run: cd current && pip --python '${{ steps.python-current.outputs.python-path }}' install ".[dev]"

      - name: Run benchmark and profiling on main and current branches
        # the same runner is used, to ensure the same underlying hardware
        # if you use different runners (or even separate commands within a run), you will notice pytest-benchmark reports machine variation
        run: >
          cd main &&
          ${{ steps.python-main.outputs.python-path }} -m pytest -m 'not third_party' --benchmark-storage='file://../current/.benchmarks' --benchmark-enable --benchmark-only --benchmark-autosave --benchmark-save-data &&
          cd ../current &&
          ${{ steps.python-current.outputs.python-path }} -m pytest -m 'not third_party' --benchmark-enable --benchmark-only --benchmark-autosave --benchmark-compare
