# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: CI
on:
  push:
    branches: [main, benchmarks] # TODO: remove benchmarks
  pull_request:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: "3.13"
    steps:
      - uses: _common.yml
      - run: pre-commit run --all-files

  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: _common.yml
      - run: pytest

  mypy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: _common.yml
      - run: mypy

  pyright:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: _common.yml
      - run: pyright
